# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('to_email', models.CharField(blank=True, max_length=255)),
                ('template', models.CharField(choices=[('emails/default_email.html', 'Generic')], default='emails/default_email.html', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
