# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationemail',
            name='template',
            field=models.CharField(choices=[('emails/generic_invite.html', 'Generic')], default='emails/generic_invite.html', max_length=255),
        ),
        migrations.AlterField(
            model_name='invitationemail',
            name='to_email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
